package indexGUI;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
import com.wiseowl.WiseOwl.indexing.FeedData;
import static indexGUI.stop_pause.comp;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.io.Writer;
import static java.lang.System.exit;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.filechooser.FileFilter;
import org.apache.solr.client.solrj.SolrServerException;

public class indexing extends javax.swing.JFrame {
    
    JFileChooser fc;
    File myfile;
    Thread t;
    Writer out = null;
    FeedData feed=null;
    long now = 0;
    /**
     * Creates new form indexing
     */
    public indexing() {
        initComponents();
    }
        public indexing(int a) {}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        start = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        choose = new javax.swing.JButton();
        default_ = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        String img_name = "ullu.png";
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        
        img = new ImageIcon(getClass().getResource(img_name));
        wiseOwlIcon = new javax.swing.JLabel(img);
        getContentPane().add(wiseOwlIcon);
        wiseOwlIcon.setBounds(160, 20, 120, 120);
        
        jLabel1.setFont(new java.awt.Font("purisa", 3, 50)); // NOI18N
        jLabel1.setText("WISEOWL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 60, 420, 70);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel2.setText("SERVER URL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 159, 100, 31);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 160, 321, 31);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel3.setText("TYPE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 279, 95, 27);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("WIKIPEDIA");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(290, 280, 100, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("OTHERS");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(437, 280, 100, 23);

        start.setText("START");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					startActionPerformed(evt);
				} catch (SolrServerException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        getContentPane().add(start);
        start.setBounds(360, 330, 113, 33);
        start.getAccessibleContext().setAccessibleDescription("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jLabel4.setText("FILE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(150, 215, 95, 32);

        choose.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        choose.setText("CHOOSE");
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        getContentPane().add(choose);
        choose.setBounds(629, 215, 100, 30);

        default_.setText("DEFAULT");
        default_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                default_ActionPerformed(evt);
            }
        });
        getContentPane().add(default_);
        default_.setBounds(629, 160, 100, 30);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jTextField2);
        jTextField2.setBounds(290, 216, 321, 31);

        setBounds(250, 200, 840, 420);
    }

    private void startActionPerformed(java.awt.event.ActionEvent evt) throws  SolrServerException {//GEN-FIRST:event_startActionPerformed
           if(jRadioButton1.isSelected())
            FeedData.indexType = jRadioButton1.getText();
                    if(jRadioButton2.isSelected())
            FeedData.indexType = jRadioButton2.getText();
                    if((FeedData.indexType != null)&&(FeedData.url != null)&&(( FeedData.filez!= null)))
                    {
                    	feed = new FeedData();
                        try {
                        	System.out.println("before "+FeedData.skip);
                                FeedData.skip = FeedData.readSkip();
                            } catch (IOException ex) {
                                Logger.getLogger(indexing.class.getName()).log(Level.SEVERE, null, ex);
                            }
                System.out.println("value of skip : "+FeedData.skip);
                if((FeedData.skip)==-1) 
                {
                    //completed
                	FeedData.running=false;
                	JOptionPane.showMessageDialog(rootPane, "File Already Indexed");
                	return;
                }
                else if((FeedData.skip)==-2)
				{
                	try {
                		FeedData.skip=0;
						FeedData.addData(FeedData.randomAccessFile.length());
					} catch (IOException e){
						e.printStackTrace();
					}
				}   
                    System.out.println("before call to index ");
                    	FeedData.running=true;
                         Thread t,t1;
                         t=new Thread(new Runnable(){
                             public void run()
                             {   
                            	 stop_pause ps = new stop_pause();
                            	 ps.setVisible(true);
                             }});
                            // Start thread
                         System.out.println("before starting t ");
                            t.start();
                            t1=new Thread(new Runnable(){
                                public void run()
                                {   
                                	try {
            							feed.index();
            						} catch (IOException e) {
            							e.printStackTrace();
            						} catch (SolrServerException e) {
										e.printStackTrace();
									}
                                	return;
                                }});
                               // Start thread
                               t1.start();
                    	System.out.println("after call to index ");
                   setVisible(false);
                }
                else
                    {
                        JOptionPane.showMessageDialog(rootPane, "FILL ALL THE FIELDS ");
                    }
    }
    
    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {
        fc = new JFileChooser();
        fc.setCurrentDirectory(new File("."));
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int result = fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            myfile = fc.getSelectedFile();
            FeedData.filez=myfile.toPath().toString();
            FeedData.name=myfile.getName();
            jTextField2.setText(FeedData.name);   
        }
    }
    
    private void default_ActionPerformed(java.awt.event.ActionEvent evt) {
        FeedData.url = "http://localhost:8983/solr/WiseOwl";
        jTextField1.setText(FeedData.url);
    }
    
    public static void main(String args[]) {
       /** Set the Nimbus look and feel 
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(indexing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(indexing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(indexing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(indexing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                indexing in=new indexing();
                in.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton choose;
    private javax.swing.JButton default_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.Icon img=null;
    private javax.swing.JLabel wiseOwlIcon;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables

}